[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.7.6"
remappings = [
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]
eth_rpc_url = 'https://rpc.mevblocker.io/noreverts'

[profile.default.optimizer_details]
yul = false

[rpc_endpoints]
mainnet = "https://rpc.mevblocker.io/noreverts"
anvil = "http://localhost:8545"

[profile.default.fs]
fs_permissions = [{ access = "read", path = "data"}]